### ISSUE TITLE
Python 3: Segfault

### ISSUE THREAD

**Issue by dglava** [keithgg/puddletag#355]
I noticed that there's a first preliminary Python 3 version out, so I thought I'd start testing it.
After installation, this is the error I'm getting:

```
puddletag Version: 1.2.0
Locale: en_US
<PyQt4.QtCore.QSettings object at 0x7f04c4a29318>
Traceback (most recent call last):
  File "/usr/bin/puddletag", line 342, in <module>
    win = MainWin()
  File "/usr/lib/python3.6/site-packages/puddlestuff/puddletag.py", line 324, in __init__
    winactions, self._docks = create_tool_windows(self)
  File "/usr/lib/python3.6/site-packages/puddlestuff/puddletag.py", line 100, in create_tool_windows
    p = PuddleDock(z[0], z[1], parent, status)
  File "/usr/lib/python3.6/site-packages/puddlestuff/puddleobjects.py", line 2194, in __init__
    control = control(status=status)
  File "/usr/lib/python3.6/site-packages/puddlestuff/masstag/dialogs.py", line 496, in __init__
    winsettings('masstaglog', self)
  File "/usr/lib/python3.6/site-packages/puddlestuff/puddleobjects.py", line 280, in <lambda>
    return lambda x, y: func(x, y, settings)
  File "/usr/lib/python3.6/site-packages/puddlestuff/puddleobjects.py", line 289, in winsettings
    dialog.restoreGeometry(settings.value(name))
TypeError: restoreGeometry(self, Union[QByteArray, bytes, bytearray]): argument 1 has unexpected type 'NoneType'
Segmentation fault (core dumped)
```

Puddletag: latest build from the py3 branch.
Python: 3.6.1
Qt version: 4.8.7
Python-pyqt4: 4.12
All running on Arch Linux.

**Comment by keithgg** [comment]
Thanks. Fixed in 1b6a5e9. Remember not to use this for anything.

I changed the config dir to ~/config/puddletag2 so that it doesn't conflict with normal puddletag settings.

**Comment by dglava** [comment]
>Remember not to use this for anything.

Because it might mess with my audio files (I don't mind mistagged files, I can just fix it later with the Python 2 version) or do you mean it doesn't work at all yet?
I wouldn't mind testing the Python 3 port.

Anyway, thanks for fixing this, but now another segfault popped up. Should I bother reporting these or is the Python 3 version still not good enough for bare usage (not running at all)?
```
Traceback (most recent call last):
  File "/usr/bin/puddletag", line 343, in <module>
    win = MainWin()
  File "/usr/lib/python3.6/site-packages/puddlestuff/puddletag.py", line 329, in __init__
    menus = ls.get_menus('menu')
  File "/usr/lib/python3.6/site-packages/puddlestuff/loadshortcuts.py", line 50, in get_menus
    menus = [(z, temp[z]) for z in settings[section + 'attrs']['order']]
KeyError: 'order'
Segmentation fault (core dumped)
```

**Comment by keithgg** [comment]
Weird one that, but fixable.

Doesn't work at all and won't even be in an alpha state for a while yet (at least a month). Don't use unless you feel like getting super frustrated that nothing's working.
